# when push event  happen to branch master , i want to update submodule that is inside other repo (https://github.com/keoKAY/spring-boot-gradle-swagger)
name: Update submodule on swagger repo 
on: 
  push:
    branches:
      - master
jobs:
    update-repo2: 
      runs-on:  ubnutu-latest
    
      steps:
        - name: Checkout first repo 
          uses: actions/checkout@v2
        - name: Update repo2 submodule
          run: 
            git submodule update --update --merge
            git push origin master

      
      

